version: '3.4'
services:
  workflow-summary-share:
    image: alfresco-share-workflow-summary:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../workflow-summary-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: workflow-summary-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  workflow-summary-acs:
    image: alfresco-content-services-workflow-summary:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../workflow-summary-platform-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - workflow-summary-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - workflow-summary-postgres
  workflow-summary-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - workflow-summary-db-volume:/var/lib/postgresql/data
  workflow-summary-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: workflow-summary-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: workflow-summary-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - workflow-summary-ass-volume:/opt/alfresco-search-services/contentstore
      - workflow-summary-ass-volume:/opt/alfresco-search-services/data
volumes:
  workflow-summary-acs-volume:
    external: true
  workflow-summary-db-volume:
    external: true
  workflow-summary-ass-volume:
    external: true